version: '3'

services:
  postgresql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./internal/storage/sql/schema/dump.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - calendar-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  amqp:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./testdata/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./testdata/rabbitmq.json:/etc/rabbitmq/definitions.json
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  calendar-data:
